In [3]:
import numpy as np
import cv2

In [4]:
# !wget https://raw.githubusercontent.com/pauldebayan/ml_notebooks/main/images/flemingo.jpg

In [5]:
!ls

ComputerVision_OpenCV.ipynb


In [10]:
img = cv2.imread('../images/flemingo.jpg')

In [11]:
print(img)

[[[189 164 120]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 [[189 164 120]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 [[189 164 120]
  [189 164 120]
  [189 164 120]
  ...
  [188 163 119]
  [188 163 119]
  [188 163 119]]

 ...

 [[161 128  82]
  [161 128  82]
  [161 128  82]
  ...
  [174 140  94]
  [174 140  94]
  [174 140  94]]

 [[168 135  89]
  [169 136  90]
  [170 137  91]
  ...
  [178 144  98]
  [178 144  98]
  [178 144  98]]

 [[176 143  97]
  [177 144  98]
  [178 145  99]
  ...
  [180 146 100]
  [180 146 100]
  [180 146 100]]]


In [12]:
img.shape

(400, 400, 3)

OpenCV by default reads BGR and not RGB

In [ ]:
# This does not work in Google Colab - use Jupyter Notebook in device
cv2.imshow('window', img)
#cv2.waitKey(10000)
cv2.waitKey(0) # instead of disapperaing after 10 seconds - wait for a key press

cv2.destroyWindow('window')

## Save the file

> cv2.imwrite('where to store', array_name)

In [ ]:
# !ls
cv2.imwrite('../images/output.png', img)

## RGB

![rgb.png](../images/rgb.jpg)

## Converting Color

![Convert Color](../images/convert_color.jpg)

> All images that we are going to study are all unsigned 8-bit integers

If it is n-bit Image than:
2^3 or 2^n
![N-Bit Image](images/nBitIntegers.jpg

In [ ]:
img

In [ ]:
img.shape

## We will spread the matrix into 3 parts - BGR

In [ ]:
img = cv2.imread('../images/RGB_Color.png')
b, g, r = cv2.split(img)

In [ ]:
b # 255 is pure blue

## Lighter Means more closer to that color

In [ ]:
#cv2.imshow('RGB Color', img)
cv2.imshow('Blue Color', b)
cv2.imshow('Red Color', r)
cv2.imshow('Green Color', g)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Color Converter

In [ ]:
img = cv2.imread('../images/flemingo.jpg')
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
#Gray
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2.imshow('BGR', img)
cv2.imshow('RGB Color', img_rgb) # BGR -> RGB, Blue is replaced by Red and vice versa
cv2.imshow('GRAY Color', gray)

cv2.waitKey(0)
cv2.destroyAllWindows()